// const specialties = [
//   { name: "Dentist", url: "#", specialty: "SPECIALITY" },
//   { name: "Gynecologist/obstetrician", url: "#", specialty: "SPECIALITY" },
//   { name: "General Physician", url: "#", specialty: "SPECIALITY" },
//   { name: "Dermatologist", url: "#", specialty: "SPECIALITY" },
//   {
//     name: "Ear-nose-throat (ent) Specialist",
//     url: "#",
//     specialty: "SPECIALITY",
//   },
//   { name: "Homeopath", url: "#", specialty: "SPECIALITY" },
//   { name: "Cardiologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Pediatrician", url: "#", specialty: "SPECIALITY" },
//   { name: "Orthopedic Surgeon", url: "#", specialty: "SPECIALITY" },
//   { name: "Neurologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Psychiatrist", url: "#", specialty: "SPECIALITY" },
//   { name: "Oncologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Endocrinologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Nephrologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Urologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Gastroenterologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Pulmonologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Rheumatologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Allergist/Immunologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Ophthalmologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Plastic Surgeon", url: "#", specialty: "SPECIALITY" },
//   { name: "Vascular Surgeon", url: "#", specialty: "SPECIALITY" },
//   { name: "Hematologist", url: "#", specialty: "SPECIALITY" },
//   { name: "Infectious Disease Specialist", url: "#", specialty: "SPECIALITY" },
//   { name: "Geriatrician", url: "#", specialty: "SPECIALITY" },
//   { name: "Podiatrist", url: "#", specialty: "SPECIALITY" },
//   { name: "Chiropractor", url: "#", specialty: "SPECIALITY" },
//   { name: "Pain Management Specialist", url: "#", specialty: "SPECIALITY" },
//   { name: "Sports Medicine Specialist", url: "#", specialty: "SPECIALITY" },
//   { name: "Occupational Therapist", url: "#", specialty: "SPECIALITY" },
//   { name: "Speech Therapist", url: "#", specialty: "SPECIALITY" },
//   { name: "Dietitian/Nutritionist", url: "#", specialty: "SPECIALITY" },
// ];
